### ISSUE TITLE
Code Builder Dashboard not updating Last Accessed

### ISSUE THREAD

**Issue by thedanfernandez** [forcedotcom/try-code-builder-feedback#138] opened 2022-04-06 00:06 UTC
**Describe the bug**
A clear and concise description of the bug. What were you trying to do? What was your goal?

The "Last Accessed" field in the Code Builder Dashboard says "never"

**To Reproduce**
1. Go to Code Builder Dashboard, see list of environments, see Last Accessed is not updating

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  They really help!

![image](https://user-images.githubusercontent.com/8809372/161870225-df2ace89-d1e8-4c67-a079-fefe65b740a5.png)

**Desktop (please complete the following information):**
OS: [e.g. iOS] MacOS Monterey
Browser [e.g. chrome, safari] Chrome
Version [e.g. 22] Version 100.0.4896.75 (Official Build) (x86_64)

**Additional context**

**Comment by FabienTaillon** [comment] 2022-05-23 16:24
Duplicate of #128

**Closed** 2022-05-23 19:31 UTC
Labels: type:bug, area:dashboard
