### ISSUE TITLE
CodeBuilder.ResourceApiResponseException

### ISSUE THREAD

**Issue by Abhishekrazy** [forcedotcom/try-code-builder-feedback#157] opened 2022-07-16 18:26 UTC
500 {
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "An internal server error occurred"
}

This error showing while creating the workspace.
first its taking too much time to create and then its showing this error.

**Comment by smaddox-sf** [comment] 2022-07-18 01:29
Duplicate of #159

**Closed by smaddox-sf** 2022-07-18 01:29 UTC
