### ISSUE TITLE
Concerning message about "unofficial" extensions

### ISSUE THREAD

**Issue by randi274** [forcedotcom/try-code-builder-feedback#125] opened 2022-04-05 21:57 UTC
**General feedback**
When I go to the Extensions tab, I see a concerning message: "WARNING: These extensions are not official" ... but then the first several extensions *are* our official Salesforce extensions. Can we modify this to be less alarmist?
![Screen Shot 2022-04-05 at 5 35 05 PM](https://user-images.githubusercontent.com/9795193/161856536-bfaebae1-e23d-441a-b0c8-750947171fc0.png)

**Comment by jgellin-sf** [comment] 2022-04-11 17:28
This may be resolved by an update to code-server. See https://github.com/forcedotcom/code-builder-images/pull/52.

**Comment by dobladez** [comment] 2022-04-27 17:40
I confirm it's gone on the latest version of code-server.

It was originally added by this PR: https://github.com/coder/code-server/pull/2501
And later removed (since version 3.12) with this commit: https://github.com/coder/code-server/commit/c8f0d3e32d1b75401c0ce118b98d862d0a228345

(not sure if the removal of this particular "feature" was intentional, but it was removed).

I've also tested both before and after our upgrade, and confirmed it used to be there, and now it's gone. Tried with a clean browser, since it used to save the user's "acknowledgement" of the warning in local-storage.

**Closed** 2022-06-15 22:02 UTC
Labels: Required for Beta, Discussion
