### ISSUE TITLE
Hours Remaining continues to drop after closing tab

### ISSUE THREAD

**Issue by eburtness** [forcedotcom/try-code-builder-feedback#173] opened 2022-07-25 21:28 UTC
**Description**
After closing the Code Builder tab, usage time continues to be counted for an additional 20-30 minutes. How can I stop the clock when I'm done using it?

**To Reproduce**
1. Launch Code Builder
2. Do something in Code Builder (I fetched from my repo and deleted a branch I no longer needed)
3. Close the browser tab
4. Refresh Code Builder Dashboard and note hours remaining (in my case it was 16:40)
5. Verify that Code Builder is not open in another tab
6. Come back later and refresh Code Builder Dashboard; note that hours remaining has decreased (I saw it continue to tick down until it stopped at 16:18 as shown below)

**Expected behavior**
Hours Remaining to stay constant when no Code Builder tabs are open

**Screenshots**
![image](https://user-images.githubusercontent.com/39753627/180876307-2c9ae06d-a1eb-47db-9345-b79fc7da965b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 21H2 (OS Build 19044.1826)
 - Browser: Chrome
 - Version: 103.0.5060.134

**Additional context**
[Overview doc](https://developer.salesforce.com/tools/vscode/en/codebuilder/about) says "We highly recommend that you save your work and close the browser tab that is running Code Builder to stop the usage clock when you aren’t using Code Builder." This sounds like all you have to do is close the tab to stop the clock.

**Comment by smaddox-sf** [comment] 2022-07-26 14:53
May be a duplicate of #164 and #158

**Comment by smaddox-sf** [comment] 2022-07-28 20:57
Hi @eburtness - Thanks for trying out Code Builder and giving us feedback.  Behind the scenes, we have some checks to try to detect when you are idle.  When you close a tab or go idle, the session time should be within about 15-30 minutes of the rough time.  We capped the hours per month for beta so that we could offer an open beta for anyone to try.  Do you still have time remaining this month?

**Comment by eburtness** [comment] 2022-07-28 22:11
Hi @smaddox-sf, thanks for looking into this. Yes, I still have time remaining. If the cap is only for the beta then I think this is not a problem and I was just overly worried at seeing my time run down. :)

I haven't seen it run for more than 30 minutes after I closed the tab, so it sounds like that is the expected behavior and we're fine! Feel free to close the issue. Thanks!

**Closed** 2022-07-29 16:41 UTC
Labels: area:General Feedback, area:Utilization

**Comment by liuxiachanghong** [comment] 2022-09-23 03:48
Hi @smaddox-sf  I wonder if this issue is still ongoing? I have closed the tab (according instruction [here](https://developer.salesforce.com/tools/vscode/en/codebuilder/cb-start#:~:text=We%E2%80%99ve%20capped%20usage%20for%20beta%20at%2020%20hours%20for%20a%20maximum%20of%2030%20days.%20We%20highly%20recommend%20that%20you%20save%20your%20work%20and%20close%20the%20browser%20tab%20that%20is%20running%20Code%20Builder%20to%20stop%20the%20usage%20clock%20when%20you%20aren%E2%80%99t%20using%20it.)) but still the time-remaining counter is running. The test Code Builder got wiped out in 20h regardless the tab is closed.
