### ISSUE TITLE
Receiving post-install error.

### ISSUE THREAD

**Issue by amugfordmugford** [forcedotcom/try-code-builder-feedback#174] opened 2022-07-27 15:15 UTC
**Describe the bug**
I installed code builder per the instruction and assigned the permission set. When I try to switch to code builder I get an error and am unable to proceed.

**To Reproduce**
1. Go to app exchange and install app, admin only
2. Assign permission set to myself (admin)
3. Go into app switcher and select Code Builder

[Skip to Navigation](javascript:void(0);)[Skip to Main Content](javascript:void(0);)
Code Builder (Beta)
Code Builder (Beta)
Press Spacebar to reorder.
[Code Builder Dashboard](https://tyndaleuniversity.lightning.force.com/lightning/n/CodeBuilder__Code_Builder_Dashboard)
A Component Error has occurred!
Message
Compilation Failure
	/CodeBuilder/appInsightsService/appInsightsService.js:57,4 : LWC1001: Unexpected compilation error: Unexpected token [Compilation Failure
	/CodeBuilder/appInsightsService/appInsightsService.js:57,4 : LWC1001: Unexpected compilation error: Unexpected token]
Additional exception on component load: Compilation Failure
	/CodeBuilder/appInsightsService/appInsightsService.js:57,4 : LWC1001: Unexpected compilation error: Unexpected token. Caused by: Compilation Failure
	/CodeBuilder/appInsightsService/appInsightsService.js:57,4 : LWC1001: Unexpected compilation error: Unexpected token [Compilation Failure
	/CodeBuilder/appInsightsService/appInsightsService.js:57,4 : LWC1001: Unexpected compilation error: Unexpected token]
Component Descriptor
markup://CodeBuilder:app
File Name
https://tyndaleuniversity.lightning.force.com/libraries/force/componentLibrary.errors.js
Function
createComponentErrorProcessor
Line
9
Column
270

**Screenshots**
If applicable, add screenshots to help explain your problem.  They really help!

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.0
 - Browser Brave
 - Version v1.41.100 (July 21st, 2022)

**Additional context**
<img width="639" alt="Screenshot 2022-07-27 at 11 15 35 AM" src="https://user-images.githubusercontent.com/74738144/181284309-c85fe8a2-3641-49a4-b704-ae4626afaa6f.png">

**Comment by jgellin-sf** [comment] 2022-07-27 16:23
@amugfordmugford Thanks for your interest in Code Builder. This issue is a duplicate of https://github.com/forcedotcom/try-code-builder-feedback/issues/148. Please follow that issue for news of a fix.

**Closed by jgellin-sf** 2022-07-27 16:23 UTC

**Comment by amugfordmugford** [comment] 2022-07-27 16:26
Thank you.
