### ISSUE TITLE
Hour Limit Consumed by Environment Creation?

### ISSUE THREAD

**Issue by jkranz-rk** [forcedotcom/try-code-builder-feedback#158] opened 2022-07-16 23:52 UTC
**What is your role?**

Platform Product Manager

**What do you normally work on when building on the Salesforce Platform?**

OEM Application

**What tools do you use today to develop on the Salesforce Platform?**

VSCode, Dev Console

**How do you see Code Builder fitting into your current workflow? Will it replace any tools you are currently using?**

Unsure yet

**General feedback**

Wasn't sure whether this is a bug or feedback: I noticed the 20 hour limit starts ticking while an environment is getting created. Is that correct? If that is by design, my feedback is that the amount of time it takes to create an environment seems out of our control, and hard to understand why that would count against usage time. If that isn't by design, let me know, I can re-submit this as an Issue.

See the screenshot below, my first environment is still being created, never accessed, and my usage time is getting consumed:

![image](https://user-images.githubusercontent.com/40637750/179375390-bd8c5b4c-566f-4cb1-b250-9768a0ec64df.png)

**Comment by Insouciance** [comment] 2022-07-17 04:15
This is quite frustrating. Environment creation is currently > 30 minutes for my org and still running with no signs or indications of when it might complete. It seems unfair to have this time counted against usage.

**Comment by smaddox-sf** [comment] 2022-07-26 14:54
We are investigating this.  May be a duplicate of #164 and #173

**Comment by smaddox-sf** [comment] 2022-07-28 20:52
Hi @jkranz-rk and @Insouciance - Your startup experience is not what we’re aiming for.  Did both of your Code Builder environments load eventually?  Do you still have timing remaining?

**Closed** 2022-08-04 21:08 UTC
Labels: More information required, area:Utilization
