### ISSUE TITLE
Get Started raises LWC exception

### ISSUE THREAD

**Issue by gshaw60** [forcedotcom/try-code-builder-feedback#190] opened 2022-09-21 21:47 UTC
First time into Code Builder, clicked on Get Started and then Import from Github. Got the below exception displayed.
![image](https://user-images.githubusercontent.com/4324676/191615937-ad1cd09e-d34b-4cab-b21f-b6592c179f01.png)
using Chrome Version 105.0.5195.125 (Official Build) (x86_64) on macOS Monterey 12.6.
Installed Code Builder on Developer sandbox not Developer Edition.
Exception repeated on second attempt. Closed exception and proceeded as expected.

**Comment by smaddox-sf** [comment] 2022-09-21 23:03
Hi @gshaw60 -  This happens in orgs where LWS is enabled. The only workaround at this time is to disable LWS or use a Trailhead Playground org or [Developer Edition Orgs](https://developer.salesforce.com/signup) to try out Code Builder. The Code Builder team is working towards an LWS-compliant solution.

Closing this one as a duplicate of #148

**Closed by smaddox-sf** 2022-09-21 23:03 UTC
